### ISSUE TITLE
clang-related building problems

### ISSUE THREAD

**Issue by rchikhi** [natir/mapping2barcode#1]
On a system that does not have clang system-wide, the program cannot be compiled.

I installed clang via miniconda and informed rust where clang is:

`declare -x LIBCLANG_PATH="/home/rxc48/miniconda3/lib"`

Building mapping2barcode with:
`
cargo install --git https://github.com/natir/mapping2barcode.git --force`

but then cargo complains during building rust-htslib about include path:

`./htslib/htslib/hts.h:31:10: fatal error: 'stddef.h' file not found`

which can be fixed by that hack:

 ```
export C_INCLUDE_PATH=/home/rxc48/miniconda3/pkgs/clang-3.8.1-h5088ec5_0/lib/clang/3.8.1/include/
export CPLUS_INCLUDE_PATH=/home/rxc48/miniconda3/pkgs/clang-3.8.1-h5088ec5_0/lib/clang/3.8.1/include/

```

but then rust cannot build non-clang programs anymore as it's using clang includes:

```
error: failed to run custom build command for `libloading v0.5.0`                                                                                                                                                 
[..]
cargo:warning=/home/rxc48/miniconda3/pkgs/clang-3.8.1-h5088ec5_0/lib/clang/3.8.1/include/stddef.h:57:39: error: missing binary operator before token "("
```

So it seems that I can either build rust-htslib successfully using clang, or the rest, but not both

**Comment by natir** [comment]
Solve we didn't required htslib any more.
